env:
  browser: true
  es2021: true
extends:
- plugin:react/recommended
- bayathy
parser: '@typescript-eslint/parser'
parserOptions:
ecmaFeatures:
jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
"react/jsx-filename-extension": off
"no-use-before-define" : off
